### PR TITLE
Update for 1.4.22

### PR DESCRIPTION
**Pull request by gbp**

### CODE REVIEW

**Comment by gbp** [comment]
@sagepe this is based on #6 and #7. From my tests these are working well would you mind a quick look if possible.

**Comment by gbp** [comment]
Rebased to fix failings specs (due to requiring `test-unit`) in Alaveteli. See: https://github.com/mysociety/alaveteli/actions/runs/4408196416

**Comment by gbp** [comment]
This gem is running on staging.alaveteli.org. All seem to be working.

**Review by sagepe — APPROVED** [review]
Looks fine to me. From what I can see of the other PRs this is based on, we're not fundamentally changing the approach rather simply using the `mini_portile` gem to handle compilation rather than manually specifying the commands in the `Rakefile`. I don't see a problem with this - the end point should be the same.

**Comment by gbp** [comment]
Merged in 4a29015ec48e4c99d5b6dc48589c217b35f14958

**Pull request closed without merging**
